import type { Metadata } from 'next';
import Link from 'next/link';
import img1 from '../../../../courses/assets/expressions/left_to_right/side.png';
import img2 from '../../../../courses/assets/expressions/right_to_left/looking_up.png';
import img3 from '../../../../courses/assets/expressions/left_to_right/thinking.png';
import img4 from '../../../../courses/assets/expressions/right_to_left/happy.png';
import img5 from '../../../../courses/assets/expressions/left_to_right/glasses.png';
import img6 from '../../../../courses/assets/expressions/back.png';

export const metadata: Metadata = {
  title: "Ruby: Advanced Phase, Final Challenge, Knowledge Check",
};

export default function Page() {
  return (
    <div className="theme-ruby">
      <div className="wrap">
        <header className="masthead">
          <p className="kicker">Instalment 10 · Course 2 (Ruby) · Advanced phase and finish</p>
          <h1>Measuring the magic, compiling it away, and checking whether any of it stuck</h1>
          <p className="lede">Six advanced topics with real measurements, a final challenge that turns your interpreter into a compiler, forty-one questions, and everything you need to put this on GitHub.</p>
        </header>
        <div className="note">
          <h5>Verification note</h5>
          <p>Every benchmark, allocation count and code-reading answer below was produced by running the code on Ruby 3.2.3. Timings come from a single-core container, so treat ratios as meaningful and absolute numbers as indicative.</p>
        </div>
        <h2><span className="num">Part A</span>The advanced phase</h2>
        <h3>A1 · The object model as a debugging tool</h3>
        <p>
          <img className="mascot-left" src={img1.src} alt="The Mewlang cat, in a neutral curious side pose" width="120" loading="lazy" />
          Metaprogramming makes "where did this method come from?" a real question. Ruby answers it directly, and these four calls will save you hours:
        </p>
        <pre><code>{"Automation::Steps::Filter.instance_method(:matching).owner        # which module defined it\nAutomation::Steps::Filter.instance_method(:matching).source_location # file and line\nAutomation::Steps::Filter.ancestors.first(5)                      # the lookup chain\nobject.singleton_methods                                          # methods on this object alone\n"}</code></pre>
        <p>For a method generated by <code>define_method</code> inside a class macro, <code>source_location</code> points at the <em>macro</em>, not at the <code>option :matching</code> line that triggered it. That is worth knowing before it confuses you: to make generated methods self-documenting you have to record the call site yourself, exactly as Milestone 4 did for steps.</p>
        <p>The lookup chain, demonstrated:</p>
        <pre><code>{"module A; def who = \"A\"; end\nmodule B; def who = \"B\"; end\nclass C\n  include A\n  prepend B\n  def who = \"C\"\nend\np C.new.who, C.ancestors.first(4)\n"}</code></pre>
        <pre className="plain"><code>{"\"B\"\n[B, C, A, Object]\n"}</code></pre>
        <p><code>prepend</code> goes <em>before</em> the class, <code>include</code> goes after it. So a prepended module wins over the class's own method (which is why it works for instrumentation), and an included module loses to it (which is why <code>include</code> provides defaults rather than overrides). Memorising the order is less useful than remembering that <code>ancestors</code> will always tell you.</p>
        <table className="grid">
          <tbody>
            <tr>
              <th>Tool</th>
              <th>Adds methods to</th>
              <th>Position</th>
              <th>Use for</th>
            </tr>
            <tr>
              <td><code>include M</code></td>
              <td>instances</td>
              <td>after the class</td>
              <td>shared behaviour the class may override</td>
            </tr>
            <tr>
              <td><code>prepend M</code></td>
              <td>instances</td>
              <td>before the class</td>
              <td>wrapping with <code>super</code>: instrumentation, logging</td>
            </tr>
            <tr>
              <td><code>extend M</code></td>
              <td>the object itself</td>
              <td>its singleton class</td>
              <td>class methods, per-object behaviour</td>
            </tr>
            <tr>
              <td><code>using M</code></td>
              <td>lexical scope</td>
              <td>refinement</td>
              <td>monkey-patching without global effect</td>
            </tr>
          </tbody>
        </table>
        <h3>A2 · Measure before you metaprogram</h3>
        <p>Milestone 7 replaced <code>method_missing</code> with generated methods and I claimed it was faster. Here is the number, 300,000 calls each:</p>
        <pre className="plain"><code>{"                       user     system      total        real\ndefine_method      0.019719   0.000818   0.020537 (  0.020542)\nmethod_missing     0.040257   0.000662   0.040919 (  0.040936)\n"}</code></pre>
        <p>Twice as slow, which is the shape you would predict: <code>method_missing</code> runs only <em>after</em> a full method lookup has failed, so you pay for the search and then for the dispatch. Two honest observations about that result.</p>
        <p><strong>It is only 20 nanoseconds per call.</strong> For a DSL evaluated once at startup this is irrelevant, and choosing generated methods was justified by typo detection and introspection, not speed. If someone tells you <code>method_missing</code> is "too slow" for a configuration DSL, ask them for the number.</p>
        <p><strong>Benchmark ships with Ruby.</strong> <code>benchmark/ips</code> (iterations per second, with statistical comparison) is the better tool and is a gem; the standard <code>Benchmark.bm</code> above is enough to settle a 2× question. Use the real profiler (<code>stackprof</code>, also a gem) before optimising anything in anger.</p>
        <h3>A3 · Lazy pipelines for data that does not fit</h3>
        <p>Our runner passes an Array between steps, so a pipeline over 10 million records needs 10 million records in memory. Ruby's answer is <code>Enumerator::Lazy</code>: chain <code>map</code> and <code>select</code> without materialising anything, and pull only what you consume.</p>
        <pre><code>{"def records = (1..2_000_000).lazy.map { |i| { id: i, topic: i.even? ? \"AI\" : \"bio\" } }\n\n# eager, over 200,000 records\n(1..200_000).map { |i| { id: i, topic: i.even? ? \"AI\" : \"bio\" } }\n            .select { |r| r[:topic] == \"AI\" }\n            .map { |r| r[:id] }\n            .first(5)\n\n# lazy, over 2,000,000 records\nrecords.select { |r| r[:topic] == \"AI\" }.map { |r| r[:id] }.first(5)\n"}</code></pre>
        <pre className="plain"><code>{"[2, 4, 6, 8, 10]\n[2, 4, 6, 8, 10]\neager over 200k: 0.3803s | lazy over 2M: 0.0002s\n"}</code></pre>
        <p>Same answer; the lazy version was roughly two thousand times faster over ten times as much data, because it built exactly ten records. Chained eager calls allocate a full intermediate array per step; lazy chains fuse into one pass and stop as soon as the consumer is satisfied.</p>
        <p>To support this in the gem, a step declares that it streams:</p>
        <pre><code>{"class Filter < Automation::Plugin\n  streaming true      # promises: takes an Enumerable, returns an Enumerable,\n                      # never calls #size, #sort or #to_a on its input\n\n  def call(records) = records.select { |r| matches?(r) }\nend\n"}</code></pre>
        <p>The runner then wraps the initial payload in <code>.lazy</code> when every step up to the first non-streaming one declares it, and materialises at the first step that does not. <strong>The metadata pattern from Milestone 7 makes this a five-line feature</strong>: the declaration is already the mechanism.</p>
        <p>The catch to document: a lazy payload means failures move. An exception from <code>fetch</code> no longer happens during the fetch step; it happens later, when <code>save_to</code> finally pulls a value, so your beautiful per-step error reporting blames the wrong step. Streaming and precise error attribution are in genuine tension, and the usual resolution is to materialise at well-chosen boundaries rather than everywhere or nowhere.</p>
        <h3>A4 · Concurrency, honestly</h3>
        <p>CRuby has a global VM lock, so Ruby threads do not run Ruby code in parallel. They do run <em>in parallel during I/O</em>, because the lock is released around blocking calls:</p>
        <pre><code>{"def slow_io(n) = sleep(0.05) || n\n\nserial   = Benchmark.realtime { 4.times { |i| slow_io(i) } }\nparallel = Benchmark.realtime { 4.times.map { |i| Thread.new { slow_io(i) } }.each(&:join) }\n"}</code></pre>
        <pre className="plain"><code>{"serial 0.201s | threaded 0.069s\n"}</code></pre>
        <p>Three times faster on a single core, because all four sleeps overlapped. Our pipeline steps are HTTP calls and file writes, so this is exactly the case that benefits, and a <code>fan_out</code> step that runs N sub-pipelines concurrently is worth having.</p>
        <p>Build it with a bounded pool rather than a thread per item, for the same reason Go's Milestone 11 bounded its workers:</p>
        <pre><code>{"def fan_out(items, concurrency: 8)\n  queue = Queue.new\n  items.each { |i| queue << i }\n  results = Array.new(items.size)\n\n  workers = concurrency.times.map do\n    Thread.new do\n      while (index = queue.pop(true) rescue nil)\n        results[index] = yield(items[index])\n      end\n    end\n  end\n  workers.each(&:join)\n  results\nend\n"}</code></pre>
        <p><code>Queue</code> is thread-safe and ships with Ruby; <code>pop(true)</code> is non-blocking and raises <code>ThreadError</code> when empty, which is how the workers know to stop. Writing to distinct indices of a preallocated array is safe here for the same reason it was in Go: separate slots, no resizing.</p>
        <div className="warn">
          <h5>
            <img className="mascot-right" src={img2.src} alt="The Mewlang cat, looking up with curiosity" width="120" loading="lazy" />
            What about Ractors?
          </h5>
          <p>Ractors give real parallelism for Ruby code by giving each one its own GVL, at the cost of strict isolation: objects crossing a Ractor boundary must be immutable (frozen and deeply so) or copied, and most gems are not Ractor-safe. They remain officially experimental and print a warning on first use.</p>
          <p>Our AST would actually pass the isolation test, since it is frozen <code>Data</code> all the way down, which is a pleasing accident of good design. Our <em>steps</em> would not: they close over registries, logger objects and sockets. The honest position is that Ractors are worth an afternoon of curiosity and are not yet worth building a gem's public API around. If you need CPU parallelism in Ruby today, the practical answers are multiple processes or moving the hot work into C, and if those sound unappealing, that is a reason to consider Go for that component.</p>
        </div>
        <h3>A5 · Allocation discipline</h3>
        <p>Ruby's garbage collector is good and allocation is still the main cost in most Ruby hot loops. With GC disabled to keep the measurement stable, 10,000 iterations each:</p>
        <pre className="plain"><code>{"{:unfrozen_literal => 10005,\n :frozen_literal   => 2,\n :symbol           => 2,\n :data_node        => 30005,\n :hash_node        => 20002}\n"}</code></pre>
        <ul>
          <li><strong>A string literal allocates a new object every time it is evaluated</strong> (10,005 objects), while a frozen one is deduplicated to a single object (2). That is what the <code>frozen_string_literal</code> magic comment buys, in one measurement.</li>
          <li><strong>Symbols allocate nothing</strong>, which is why identifiers in this project are symbols.</li>
          <li><strong>A <code>Data</code> node with a Hash inside costs about three objects</strong> (node, hash, and the keyword machinery) against two for a bare Hash. Immutability and value equality are not free, and at 30,000 objects per 10,000 nodes they are cheap enough that the trade is easy.</li>
        </ul>
        <p>Note the measurement technique. My first attempt, without <code>GC.disable</code>, reported <strong>negative</strong> allocations for the string case, because the collector ran mid-measurement and freed more than the loop created. <strong>Naive allocation counting is noise unless you disable the GC or use <code>ObjectSpace.trace_object_allocations</code></strong>, and a benchmark that can report a negative count is a benchmark you should not trust in either direction.</p>
        <h3>A6 · Refinements, types, and docs</h3>
        <p>Refinements are scoped monkey-patching: a change to a core class that exists only in the file or module that asks for it.</p>
        <pre><code>{"module StepSugar\n  refine Symbol do\n    def to_step = \"step(#{self})\"\n  end\nend\n\n:fetch.to_step              # => NoMethodError\n\nmodule Scoped\n  using StepSugar\n  def self.demo = :fetch.to_step\nend\n\nScoped.demo                 # => \"step(fetch)\"\n:fetch.to_step              # => NoMethodError, still\n"}</code></pre>
        <p>This is the responsible way to add methods to classes you do not own, and it is why <code>using</code> exists. We did not use refinements in the DSL for a reason worth stating: <strong>they are lexically scoped, so they do not apply inside a block that was defined elsewhere</strong>, which is precisely how our DSL blocks are evaluated. A refinement-based DSL would work in the file that declared it and mysteriously fail everywhere else.</p>
        <h4>Types for a dynamic gem</h4>
        <p>Ruby 3 ships RBS, a separate signature language, and <code>steep</code> type-checks against it:</p>
        <pre className="plain"><code>{"# sig/automation.rbs\nmodule Automation\n  class Registry\n    def register: (Symbol | String, ?_Callable, ?spec: Hash[Symbol, untyped]?, ?doc: String?)\n                  { (untyped, *untyped) -> untyped } -> self\n    def fetch: (Symbol | String, ?location: String?) -> _Callable\n    def known: () -> Array[Symbol]\n  end\n\n  interface _Callable\n    def call: (untyped, *untyped, **untyped) -> untyped\n  end\nend"}</code></pre>
        <p>Signatures live outside the code, so they can be added incrementally and do not clutter a DSL. Be realistic about coverage: the parts of this gem that are ordinary objects (registry, config, store, AST) type-check well; the parts built on <code>method_missing</code> and generated methods cannot be described at all, because their signatures do not exist until run time. <strong>A gem like this one is exactly where static typing gives least</strong>, which is worth knowing when someone proposes adding it everywhere.</p>
        <p>For documentation, YARD reads <code>@param</code>/<code>@return</code> comments and, more importantly here, lets you document methods that do not exist:</p>
        <pre className="plain"><code>{"# @!method fetch(from:, limit: nil)\n#   Fetch a JSON array of records from an HTTP endpoint.\n#   @param from [String] URL returning a JSON array\n#   @param limit [Integer, nil] keep at most this many records"}</code></pre>
        <p>That <code>@!method</code> directive is how you stop dynamic definitions from being invisible to your users. It is also a smell detector: if you cannot write the directive, your users cannot discover the method.</p>
        <h4>CI and supply chain</h4>
        <pre className="plain"><code>{"# .github/workflows/ci.yml (the shape, not the whole file)\nstrategy:\n  matrix:\n    ruby: [\"3.2\", \"3.3\", \"3.4\"]\nsteps:\n  - uses: ruby/setup-ruby@v1\n    with: { ruby-version: \"${{ matrix.ruby }}\", bundler-cache: true }\n  - run: bundle exec rake test\n  - run: bundle exec rubocop\n  - run: gem install bundler-audit && bundle audit check --update"}</code></pre>
        <p>Test the Ruby versions your gemspec claims to support, or do not claim them. <code>bundler-audit</code> checks your lockfile against known advisories, which for a gem with zero runtime dependencies is a short conversation and remains worth automating.</p>
        <hr />
        <h2><span className="num">Part B</span>The final challenge</h2>
        <h3>Compile the pipeline instead of interpreting it</h3>
        <p>
          <img className="mascot-left" src={img3.src} alt="The Mewlang cat, thinking with a paw to its chin" width="120" loading="lazy" />
          Everything so far interprets: the runner walks the AST at run time, looks each step up in a registry, and calls it. Now write a <strong>compiler</strong> that turns a pipeline into standalone Ruby source which runs with no interpreter, no registry lookups, and no dependency on this gem.
        </p>
        <pre className="plain"><code>{"$ automation compile examples/research.rb --output research_compiled.rb\n$ ruby research_compiled.rb          # no `require \"automation\"` anywhere"}</code></pre>
        <h4>Requirements</h4>
        <ol>
          <li><code>Automation::Compiler.new(registry).compile(pipeline)</code> returns a String of valid Ruby defining a single method <code>run(input = nil)</code> and calling it.</li>
          <li>Step implementations are inlined into the generated source. A step registered as a block or lambda has its source extracted; a step registered as a <code>Plugin</code> subclass has its class definition emitted.</li>
          <li>Retries, dry-run support and <code>when_failed</code> handling are generated as ordinary Ruby control flow, not as a middleware chain.</li>
          <li>The generated file has no runtime dependency on the gem and passes <code>ruby -c</code> (syntax check) and RuboCop.</li>
          <li>Compilation fails loudly, naming the step, when a step's implementation cannot be inlined.</li>
        </ol>
        <h4>Constraints</h4>
        <ul>
          <li>No <code>eval</code> in the generated code. The point is source you can read and commit.</li>
          <li>Generated code must include a header comment naming the source file, the pipeline and the gem version. </li>
          <li>String interpolation of user values must be safe: an option containing <code>"; system('rm -rf /'); "</code> must not become executable code.</li>
          <li>The compiler must not run any step.</li>
        </ul>
        <h4>Acceptance criteria</h4>
        <ol>
          <li><strong>Differential testing.</strong> For at least five pipelines, interpreted and compiled runs produce identical payloads and identical failure behaviour. Write this as a test that generates, writes, shells out to <code>ruby</code>, and compares.</li>
          <li><strong>Speed.</strong> The compiled version is measurably faster on a pipeline of ten trivial steps run 10,000 times. Report the ratio and be honest if it is small.</li>
          <li><strong>Safety.</strong> A test proves that a hostile option value ends up as data, not code.</li>
          <li><strong>Failure.</strong> Compiling a pipeline whose step was registered as a C-implemented method or an object without extractable source raises a clear error naming the step.</li>
        </ol>
        <h4>Hints</h4>
        <ul>
          <li><code>Proc#source_location</code> gives you a file and line. Getting the source <em>text</em> from that is the hard part: read the file and find the block's extent. Look at how the <code>method_source</code> gem does it, and consider whether requiring plugin classes (whose source is a whole file) rather than blocks makes the problem easier.</li>
          <li>For safe interpolation, do not build strings from user values at all. Emit <code>value.inspect</code>, which for every type we allow produces a literal that evaluates back to an equal value. Test it with a string full of quotes and interpolation markers.</li>
          <li>Generate a method per step (<code>step_1_fetch</code>) rather than one enormous method: the stack traces are better and it is easier to read.</li>
          <li>The retry logic you already wrote as middleware becomes a <code>begin/rescue/retry</code> template. Write the target code by hand first, then work backwards to the generator.</li>
        </ul>
        <p>
          <img className="mascot-right" src={img4.src} alt="The Mewlang cat, happy and celebrating" width="120" loading="lazy" />
          This is the most valuable exercise in the Ruby course, because it is the bridge to Course 5. Racket does this at compile time, with the language's own macro system, and produces better error messages while doing it. Building the clumsy version by hand is what makes the elegant version legible.
        </p>
        <details>
          <summary>Solution — only look after trying</summary>
          <h4>Shape</h4>
          <pre><code>{"module Automation\n  class Compiler\n    class NotCompilable < Error; end\n\n    def initialize(registry) = @registry = registry\n\n    def compile(pipeline)\n      steps = pipeline.steps.each_with_index.map { |step, i| compile_step(step, i) }\n\n      <<~RUBY\n        # Generated by automation #{VERSION} from #{pipeline.location}\n        # Pipeline: #{pipeline.name}. Do not edit; regenerate instead.\n        # frozen_string_literal: true\n\n        #{inlined_definitions(pipeline).join(\"\\n\\n\")}\n\n        #{steps.join(\"\\n\\n\")}\n\n        def run(input = nil)\n        #{run_body(pipeline).gsub(/^/, \"  \")}\n        end\n\n        puts run.inspect if $PROGRAM_NAME == __FILE__\n      RUBY\n    end\n\n    private\n\n    def compile_step(step, index)\n      <<~RUBY\n        def step_#{index}_#{step.name}(input)\n          #{call_expression(step)}\n        end\n      RUBY\n    end\n\n    # Values become literals via #inspect, never via interpolation.\n    def literal(value)\n      case value\n      when String, Symbol, Numeric, TrueClass, FalseClass, NilClass then value.inspect\n      when Array then \"[#{value.map { |v| literal(v) }.join(', ')}]\"\n      when Hash then \"{#{value.map { |k, v| \"#{literal(k)} => #{literal(v)}\" }.join(', ')}}\"\n      else raise NotCompilable, \"cannot compile a #{value.class} option value\"\n      end\n    end\n  end\nend\n"}</code></pre>
          <h4>The four decisions that matter</h4>
          <p><strong>1. <code>inspect</code> is the safe interpolation.</strong> For every type the allow-list permits, <code>value.inspect</code> produces a literal that evaluates back to an equal value, with quoting and escaping handled by Ruby itself. Building <code>"from: \"#{'{'}value{'}'}\""</code> by hand is how you get injection; the hostile string from the acceptance criteria comes out as an inert, correctly escaped string literal. The <code>else</code> branch is as important: refusing to compile a Proc or a socket is the right answer, not guessing.</p>
          <p><strong>2. Plugin classes compile, bare blocks mostly do not.</strong> Extracting the text of a block from its <code>source_location</code> means re-parsing the file and finding where the block ends, which is genuinely hard (<code>method_source</code> does it by trying successively longer substrings until <code>ruby -c</code> accepts them, which tells you how hard). A plugin class, by contrast, lives in a known file that you can copy wholesale. The honest resolution is that <strong>compilation is a feature of class-based steps</strong>, and the compiler raises <code>NotCompilable</code> naming any block-registered step, with a message suggesting the plugin form. Discovering that a feature imposes a constraint on an earlier design decision is the normal shape of this kind of work.</p>
          <p><strong>3. Differential testing is the only credible verification.</strong></p>
          <pre><code>{"  def assert_compiles_identically(pipeline, input = nil)\n    interpreted = Automation::Runner.new(registry: test_registry).run(pipeline, input)\n\n    Dir.mktmpdir do |dir|\n      file = File.join(dir, \"compiled.rb\")\n      File.write(file, Automation::Compiler.new(test_registry).compile(pipeline))\n\n      assert system(\"ruby\", \"-c\", file, out: File::NULL), \"generated code is not valid Ruby\"\n\n      compiled = `ruby #{file}`.chomp\n      assert_equal interpreted.payload.inspect, compiled\n    end\n  end\n"}</code></pre>
          <p>Two implementations, one specification, compared on real inputs. This is the same technique compiler authors use against a reference interpreter, and it is the only way to have confidence in a generator: unit-testing the generated <em>string</em> tests your formatting, not your semantics.</p>
          <p><strong>4. The speed result is probably disappointing, and that is the lesson.</strong> Expect something between 1.2× and 2× on trivial steps. The interpreter's overhead is a registry lookup and a few lambda calls per step; if your steps do any real work (an HTTP request, a regex over a megabyte), that overhead is noise. <strong>Compilation's real payoff here is not speed, it is artefact independence</strong>: a single reviewable file you can commit, audit, ship to a machine that does not have your gem, and diff when it changes. Say so in your README rather than claiming a performance win you cannot substantiate. </p>
          <h4>What this teaches about Course 5</h4>
          <p>Notice what was painful: getting at the source text of user code, generating syntactically valid output by string concatenation, keeping the generated code readable, and producing errors that point at the user's file. All four are string-level problems, because Ruby gives you no access to its own syntax as data.</p>
          <p>Racket's macros operate on <em>syntax objects</em>: structured, already-parsed code that carries its own source locations and binding information. The equivalent compiler there is not a string generator; it is a function from syntax to syntax, it cannot produce invalid output, and error messages point at the user's line for free. When you meet that in Course 5, this challenge is the thing it will be compared against.</p>
        </details>
        <hr />
        <h2><span className="num">Part C</span>Knowledge check</h2>
        <h3>C1 · Twenty conceptual questions</h3>
        <ol className="qs">
          <li>Explain what <code>instance_eval</code> changes and what it leaves alone. Name the four kinds of identifier and how each behaves inside the block.</li>
          <li>Why is <code>BasicObject</code> the right superclass for a DSL builder, and what does it cost?</li>
          <li>What is a <code>Binding</code>, and what is <code>block.binding.receiver</code> used for here? What is the conservative alternative?</li>
          <li>Give three reasons the DSL builds an AST instead of executing as it parses.</li>
          <li>How does a dynamic language produce build-time errors with file and line numbers?</li>
          <li>When should you prefer <code>define_method</code> over <code>method_missing</code>, and when is <code>method_missing</code> genuinely necessary?</li>
          <li>What two methods must always be defined together, and what breaks otherwise?</li>
          <li>Explain the class-macro pattern using <code>option</code> as the example. What are the two effects of one call?</li>
          <li>Why must <code>inherited</code> call <code>super</code>?</li>
          <li>Compare <code>include</code>, <code>prepend</code>, <code>extend</code> and <code>using</code> in one sentence each.</li>
          <li>Why is a proc's <code>return</code> dangerous when you store user callbacks, and what do you use instead?</li>
          <li>When does Ruby set <code>Exception#cause</code>? Why did the runner not get one?</li>
          <li>What is the middleware fold, and why is the list reversed before folding?</li>
          <li>Why does the runner return a <code>RunResult</code> rather than raising, and what is the cost of that choice?</li>
          <li>What makes <code>from_h</code> safe for untrusted pipelines, and what would make it unsafe again?</li>
          <li>Why must policies be idempotent, and how do you detect that they are not?</li>
          <li>Why does the project produce successor pipelines instead of mutating running ones?</li>
          <li>What does the <code>frozen_string_literal</code> comment actually do, and what did it measure at?</li>
          <li>Explain Ruby's GVL in terms of what threads can and cannot speed up.</li>
          <li>For a DSL gem, what counts as a breaking change under semantic versioning?</li>
        </ol>
        <details>
          <summary>Answers to C1</summary>
          <ol className="qs">
            <li>It changes <code>self</code> for the duration of the block, and nothing else. Locals still resolve (the block is a closure), constants resolve lexically where the block was written, method calls go to the new <code>self</code> (so the caller's methods are unreachable without delegation), and instance variables resolve on the new <code>self</code>, which is why <code>@server</code> silently became <code>nil</code> in three of my tests.</li>
            <li>Because it has almost no methods, nearly every verb falls through to <code>method_missing</code> rather than hitting an inherited <code>Object</code> method. The cost is that you lose everything too: constants need <code>::</code>, <code>puts</code> and <code>raise</code> are unavailable, and plumbing methods need <code>__ugly__</code> names so they do not collide with user verbs.</li>
            <li>A <code>Binding</code> captures an execution context: local variables, <code>self</code>, and the lexical scope. <code>block.binding.receiver</code> recovers the <code>self</code> where the block was written so unknown verbs can be forwarded back to it. The conservative alternative is requiring the caller to pass it: <code>define("x", context: self)</code>, uglier and more honest.</li>
            <li>Dry runs and validation need to walk the pipeline without side effects; source locations and diffs need it to be data; and transformations need it to be a value you can produce a new version of. The invariant test <code>test_building_executes_nothing</code> pins all three.</li>
            <li>By capturing <code>caller_locations</code> at the moment each construct is built, and storing the file and line on the node. Everything downstream (validator, explain, logs, CLI) then reports the user's own file. Getting the frame depth right is experimental, and wrong depths report inside your own library.</li>
            <li>Prefer <code>define_method</code> whenever you know the names: the methods really exist, are faster, appear in <code>instance_methods</code>, and anything not caught by them is a typo you can report. <code>method_missing</code> is necessary when the set is genuinely open, and remains useful as the fallback that turns unknown names into good errors.</li>
            <li><code>method_missing</code> and <code>respond_to_missing?</code>. Without the second, <code>respond_to?</code> lies, <code>method()</code> raises <code>NameError</code>, and any library that checks before calling will skip your object.</li>
            <li><code>option :max_words, default: 10</code> records metadata in a class-level Hash <em>and</em> calls <code>define_method</code> to generate a reader. The metadata drives validation, documentation and CLI help; the reader makes <code>max_words</code> work inside <code>call</code>. One declaration, two uses, which is why <code>attr_accessor</code>, <code>validates</code> and <code>let</code> all look like this.</li>
            <li>Because other libraries may define <code>inherited</code> earlier in the ancestor chain, and skipping <code>super</code> silently breaks them. The same applies to every hook: <code>included</code>, <code>method_added</code>, <code>const_missing</code>.</li>
            <li><code>include</code>: instance methods, after the class in lookup. <code>prepend</code>: instance methods, before the class, so <code>super</code> reaches the original. <code>extend</code>: methods on that object alone, via its singleton class. <code>using</code>: activates a refinement in the current lexical scope only.</li>
            <li>A <code>return</code> inside a proc returns from the enclosing <em>method</em>, so a user's handler can make your library return from somewhere unexpected; a lambda's <code>return</code> exits only the lambda. A block captured with <code>&block</code> is a proc, so store lambdas when you can, or document the hazard.</li>
            <li>Only when an exception is raised inside a <code>rescue</code> block. Our runner <em>constructs</em> <code>StepFailed</code> without raising it at that point, so no chain was recorded and the handler received the wrapper. The fix is an explicit <code>original</code> field.</li>
            <li>Each middleware is <code>(step, context, nxt)</code>; the fold wraps the innermost behaviour in each layer, producing one callable. The list is reversed so that folding produces the layers in the order written; folding forwards runs them inside-out.</li>
            <li>Because a failed run still has partial results worth showing to a CLI, a dashboard or a test, and an exception discards that context. The cost is that an ignored result is an ignored error, which bit me in Milestone 7; mitigate with <code>run!</code> at the top level or a non-zero exit code.</li>
            <li>It builds the AST from JSON with no callables anywhere, so an untrusted pipeline can only compose verbs you registered. It becomes unsafe if you register a dangerous verb (<code>:shell</code>), if you allow handlers (which are blocks), or if you skip the size and value allow-lists.</li>
            <li>Because they run on every <code>define</code>, so a policy that appends unconditionally grows the pipeline without bound. Detect it by applying policies repeatedly until the result stops changing, with a round limit; value equality on <code>Data</code> makes the fixpoint check one <code>==</code>.</li>
            <li>Because a run should have one fixed definition: logs describe something that still exists, a bad transformation is discarded rather than corrupting a live run, and the runner never has to handle steps appearing mid-flight. Query planners and JIT compilers work this way too.</li>
            <li>It freezes every string literal in the file, so identical literals are deduplicated into one object. Measured: 10,005 objects allocated for 10,000 unfrozen literals against 2 for frozen ones.</li>
            <li>CRuby's global VM lock means only one thread runs Ruby bytecode at a time, so threads do not speed up CPU work. The lock is released around blocking I/O, so they do help there: four 50 ms sleeps took 201 ms serially and 69 ms threaded.</li>
            <li>Anything that changes the meaning of a pipeline file: renaming a verb or an option, changing a default, making an optional option required, or changing what a step returns. None of these is a Ruby method signature change, which is why the usual "public API" framing misleads for DSL gems. </li>
          </ol>
        </details>
        <h3>C2 · Ten code-reading questions</h3>
        <p>Predict the output. All ten were run; answers below.</p>
        <pre><code>{"# 1\nmodule A; def who = \"A\"; end\nmodule B; def who = \"B\"; end\nclass C\n  include A\n  prepend B\n  def who = \"C\"\nend\np C.new.who, C.ancestors.first(4)\n\n# 2\ndef run_block = [yield(1, 2, 3), block_given?]\np run_block { |a, b| [a, b] }\n\n# 3  (no frozen_string_literal comment in this file)\ns = \"abc\".dup\ns << \"d\"\np s, s.frozen?, \"abc\".frozen?\n\n# 4\nPoint = Struct.new(:x, :y)\npt = Point.new(1, 2)\npt.x = 9\nD = Data.define(:x, :y)\nd = D.new(x: 1, y: 2)\np pt.to_a, d.with(x: 9), d.respond_to?(:x=)\n\n# 5\ndef f(a, *rest, k: 1, **opts) = [a, rest, k, opts]\np f(1, 2, 3, k: 4, z: 5)\nh = { k: 9, z: 8 }\np f(1, **h)\np f(1, h)\n\n# 6\n@a = false\n@a ||= \"set\"\n@b = nil\n@b ||= \"set\"\np @a, @b\n\n# 7\np([1, 2, 3].reduce([]) { |acc, n| acc << n * 2 })\np([1, 2, 3].reduce(0) { |acc, n| acc + n if n.odd? })\n\n# 8\nclass Gen\n  limit = 3\n  define_method(:with_closure) { limit }\n  def with_def = defined?(limit) ? limit : \"limit is not visible here\"\nend\np Gen.new.with_closure, Gen.new.with_def\n\n# 9\nclass Ghost\n  def method_missing(n, *) = n.to_s.start_with?(\"go_\") ? :ok : super\nend\ng = Ghost.new\np g.go_home, g.respond_to?(:go_home)\n\n# 10\nclass Widget; end\nWidget.class_eval { def hello = \"instance method\" }\nWidget.instance_eval { def hi = \"class method\" }\np Widget.new.hello, Widget.hi\n"}</code></pre>
        <details>
          <summary>Answers to C2</summary>
          <pre className="plain"><code>{"1.  \"B\"  /  [B, C, A, Object]\n2.  [[1, 2], true]\n3.  \"abcd\"  /  false  /  false\n4.  [9, 2]  /  #<data D x=9, y=2>  /  false\n5.  [1, [2, 3], 4, {:z=>5}]\n    [1, [], 9, {:z=>8}]\n    [1, [{:k=>9, :z=>8}], 1, {}]\n6.  \"set\"  /  \"set\"\n7.  [2, 4, 6]  then NoMethodError (nil accumulator)\n8.  3  /  \"limit is not visible here\"\n9.  :ok  /  false\n10. \"instance method\"  /  \"class method\"\n"}</code></pre>
          <ol className="qs">
            <li><code>prepend</code> puts B before C in the chain, so B wins over the class's own method. <code>include</code> puts A after C, so A never gets a look in.</li>
            <li>Blocks are lenient about arity: three yielded values, two parameters, the third is dropped. A lambda would have raised <code>ArgumentError</code>.</li>
            <li>Without the magic comment, string literals are unfrozen, so <code>"abc".frozen?</code> is <code>false</code>. Add <code># frozen_string_literal: true</code> at the top and the third value becomes <code>true</code>. The answer to a question about Ruby strings genuinely depends on a comment.</li>
            <li><code>Struct</code> is mutable and positional; <code>Data</code> is immutable with keyword construction, <code>with</code> for copies, and no writers at all.</li>
            <li>The first two lines show splat and double-splat collecting. The third is the Ruby 3 separation: a bare Hash is <em>positional</em>, so it lands in <code>rest</code> and <code>k</code> keeps its default. In Ruby 2 this was auto-converted to keywords, and the change broke a great deal of code. </li>
            <li><code>||=</code> assigns when the current value is <code>nil</code> <em>or</em> <code>false</code>. Using it to memoise a legitimately false value re-evaluates every time; use <code>defined?</code> or a Hash with <code>key?</code> when false is a real answer.</li>
            <li><code>acc {'<'}{'<'} n * 2</code> works because <code>{'<'}{'<'}</code> returns the array. The second raises because when <code>n</code> is even the block returns <code>nil</code>, and the next iteration calls <code>nil + n</code>. <strong>In <code>reduce</code>, the block's return value <em>is</em> the accumulator</strong>, which is why <code>each_with_object</code> is safer when you are building something.</li>
            <li><code>define_method</code> takes a block, and blocks are closures, so <code>limit</code> is captured. <code>def</code> opens a new scope and sees nothing from the class body. This is the main practical reason to reach for <code>define_method</code>.</li>
            <li><code>method_missing</code> handles the call, but <code>respond_to?</code> has no idea, because <code>respond_to_missing?</code> was not defined. The object works and lies about itself.</li>
            <li><code>class_eval</code> evaluates in the context of the class, so <code>def</code> defines an instance method. <code>instance_eval</code> evaluates with the class as <code>self</code>, so <code>def</code> defines a method on the class object, that is, a class method. The names feel backwards to everyone at first.</li>
          </ol>
        </details>
        <h3>C3 · Five debugging exercises</h3>
        <ol className="qs">
          <li>
            <strong>Symptom:</strong> a pipeline built in a test has one step instead of two, no error, no warning. 
            <pre className="bad"><code>{"summarize = stub_step(:summarize) { |items| items.first(2) }\npipeline = build_pipeline(\"t\") do\n  fetch from: \"x\"\n  summarize\nend"}</code></pre>
          </li>
          <li>
            <strong>Symptom:</strong> <code>explain</code> reports every step's location as <code>define.rb:113</code> instead of the user's file. 
            <pre className="bad"><code>{"def __where__\n  frame = ::Kernel.caller_locations(1, 1).first\n  \"#{::File.basename(frame.path)}:#{frame.lineno}\"\nend"}</code></pre>
          </li>
          <li>
            <strong>Symptom:</strong> a <code>when_failed</code> handler prints <code>step fetch failed: step fetch failed: timeout</code>, doubled. 
            <pre className="bad"><code>{"handler.callable.call(error, step)   # error is the StepFailed wrapper"}</code></pre>
          </li>
          <li>
            <strong>Symptom:</strong> after adding a policy, every <code>define</code> is slower than the last and eventually raises "rewrite produced 501 steps". 
            <pre className="bad"><code>{"Automation::Policies.register(:audit) do |pl|\n  pl.rewrite { append step(:audit_log) }\nend"}</code></pre>
          </li>
          <li>
            <strong>Symptom:</strong> a third-party step works when registered as a lambda and crashes the validator when registered as a custom object. 
            <pre className="bad"><code>{"params = @registry.fetch(step.name).parameters"}</code></pre>
          </li>
        </ol>
        <details>
          <summary>Answers to C3</summary>
          <ol className="qs">
            <li><strong>A local variable shadowed the verb.</strong> Once Ruby's parser has seen <code>summarize = ...</code>, the bare word <code>summarize</code> inside the block is that variable, not a method call, so no step is added. Rename the local (<code>summarizer</code>) or force a call with <code>summarize()</code>. Diagnose it by printing <code>pipeline.step_names</code>, which is faster than staring at the block.</li>
            <li><strong>Wrong stack depth.</strong> <code>caller_locations(1, 1)</code> from inside <code>__where__</code> returns <code>__where__</code>'s caller, which is your own <code>method_missing</code> or <code>__add_step__</code>, not the user. Count the frames experimentally and pin the result with a test asserting the location matches the test file's own name, which is what stops the bug returning.</li>
            <li><strong>Passing the wrapper instead of the original.</strong> The handler should receive the cause: <code>error.respond_to?(:original) ? error.original : error</code>. The doubled message is the tell: your wrapper's message already contains the inner message, so printing the wrapper inside a message that describes the step says everything twice.</li>
            <li><strong>A non-idempotent policy.</strong> It appends unconditionally, so every application adds another <code>audit_log</code>, and policies run on every <code>define</code> including on pipelines produced by rewrites. Guard it: <code>pl.find(:audit_log) ? pl : pl.rewrite {'{'} ... {'}'}</code>. The step limit turning it into an error rather than an out-of-memory crash is the limit doing its job.</li>
            <li><strong>A duck-typing assumption.</strong> The registry accepts anything with <code>#call</code>, but the validator additionally requires <code>#parameters</code>, which lambdas and Methods have and arbitrary objects do not. Ask for <code>impl.method(:call).parameters</code> instead, and return <code>nil</code> (meaning "cannot check") rather than raising for anything that cannot answer.</li>
          </ol>
        </details>
        <h3>C4 · Five implementation exercises</h3>
        <ol className="qs">
          <li><strong>Conditional steps.</strong> Add <code>only_if</code> and <code>unless</code> options evaluated at run time against the context vars, so <code>fetch from: url, only_if: :full_refresh</code> is skipped unless the var is set. The result must record the step as <code>:skipped</code>, and <code>explain</code> must show the condition.</li>
          <li><strong>Sub-pipelines.</strong> Let a pipeline include another by name (<code>include_pipeline "cleanup"</code>), with cycle detection and a clear error naming the cycle.</li>
          <li><strong>Parallel fan-out.</strong> Implement a <code>fan_out</code> step that runs several sub-pipelines concurrently with a bounded thread pool, merges their payloads, and reports the slowest branch.</li>
          <li><strong>Persistence and resume.</strong> Checkpoint the payload after each step so an interrupted run can resume from the last completed step. Decide what makes a payload safely resumable and document the limits.</li>
          <li><strong>A second front end.</strong> Write a YAML loader producing the same AST as the Ruby DSL, with the same validation and source locations (YAML parsers can report line numbers). Prove with a test that the two front ends produce equal pipelines for equivalent input.</li>
        </ol>
        <h3>C5 · One substantial challenge</h3>
        <p><strong>Build a language server for your DSL.</strong> Implement a minimal LSP server (stdin/stdout, JSON-RPC) that gives an editor: completion for step names with their documentation, hover showing a step's options and defaults, and diagnostics from the validator with correct ranges, for any file using your gem. </p>
        <p>Requirements: it must derive everything from the registry rather than a hard-coded list, so a user's plugins appear automatically; diagnostics must update on save; and it must not execute the pipeline file more than once per change. Hints: the hard part is not the protocol (it is a few message types) but deciding <em>when</em> it is safe to load a user's file, given that loading is executing. Think about a subprocess, a timeout, and what to do when the file has a syntax error.</p>
        <h3>C6 · You should now be able to explain</h3>
        <ul>
          <li>What <code>instance_eval</code> changes, and all four identifier behaviours inside a block.</li>
          <li>The Ruby object model: singleton classes, ancestor chains, and method lookup.</li>
          <li>When metaprogramming is the right tool and the specific costs it imposes on tooling.</li>
          <li>Why an AST is the load-bearing idea in a DSL, not the syntax.</li>
          <li>How a dynamic language produces build-time errors with source locations.</li>
          <li>The class-macro pattern, and therefore how Rails, RSpec and most Ruby libraries work.</li>
          <li>Blocks, procs and lambdas, including the <code>return</code> hazard.</li>
          <li>Exception hierarchies, wrapping, and the limits of <code>cause</code>.</li>
          <li>The middleware pattern and how the chain is built.</li>
          <li>Why executable configuration is remote code execution, and where the trust boundary goes.</li>
          <li>Lazy enumerators, and the tension between streaming and error attribution.</li>
          <li>The GVL: what threads can and cannot make faster.</li>
          <li>Why transformations produce successors rather than mutating.</li>
        </ul>
        <h3>C7 · You should now be able to implement</h3>
        <ul>
          <li>An internal DSL with <code>instance_eval</code>, delegation to the caller, and collision-safe plumbing. </li>
          <li>An immutable AST with source locations, value equality and safe transformations.</li>
          <li>A validator that reports every problem at once with file and line.</li>
          <li>A plugin system with class macros, declared metadata and generated readers.</li>
          <li>An interpreter with a context, middleware, retries and failure handlers.</li>
          <li>Testing helpers other people can use: spies, isolated registries, domain assertions, contract tests. </li>
          <li>Self-description: explain, diagrams, diffs.</li>
          <li>A rewrite API and an idempotent policy layer.</li>
          <li>A gem with a CLI, honest exit codes, a changelog and zero runtime dependencies.</li>
          <li>A data-only loading path for untrusted input, with allow-lists and size bounds.</li>
        </ul>
        <hr />
        <h2><span className="num">Part D</span>Shipping it: README, portfolio, interview</h2>
        <h3>D1 · README draft</h3>
        <pre className="plain"><code>{"# automation\n\nA Ruby DSL for describing automation pipelines, with the unusual property\nthat a pipeline is **data you can inspect, validate, diagram and rewrite**\nbefore anything runs.\n\nNo runtime dependencies. Ruby 3.2+.\n\n```ruby\nAutomation.define(\"research\") do\n  retry_on Automation::HttpError, times: 3, backoff: :exponential\n\n  fetch     from: \"https://example.com/papers.json\", limit: 20\n  filter    field: :topic, matching: \"AI\"\n  summarize field: :abstract, max_words: 40\n  save_to   collection: \"knowledge_base\"\n\n  when_failed { |error, step| warn \"#{step.name}: #{error.message}\" }\nend\n```\n\n    $ automation explain examples/research.rb\n    $ automation run examples/research.rb --dry-run\n    $ automation graph examples/research.rb > pipeline.mmd\n\n## Why this exists\n\nEvery team eventually writes a YAML file that wants to be a program, then\ninvents conditionals, loops and variables badly. This starts from the other\nend: it is Ruby, so loops and conditionals were always there, and the DSL is\na thin surface over an AST that the tooling can reason about.\n\n## What you get\n\n- **Errors before anything runs**, with your file and line:\n\n      pipeline is invalid:\n        - research.rb:7: step fetch is missing required option :from\n        - research.rb:8: unknown step :summarise; did you mean summarize?\n        - research.rb:9: step filter got unknown option :limit; it accepts: field, matching\n\n- **Dry runs** that provably touch nothing (there is a test asserting the\n  fake HTTP server receives zero requests).\n- **Retries** with linear or exponential backoff, and failure handlers.\n- **Inspection**: `explain`, Mermaid diagrams, and diffs between versions.\n- **Rewriting**: pipelines are values, so transformations produce new ones.\n- **Policies**: organisation-wide rules applied to every pipeline at define\n  time (always log first, cap expensive options, require a retry policy).\n- **A safe mode**: load pipelines from JSON, executing no code at all.\n- **Testing helpers** for your own pipelines and plugins.\n\n## Adding a step\n\n```ruby\nclass Translate < Automation::Plugin\n  step_name :translate\n  doc \"Translate a field into another language.\"\n\n  option :field, default: :abstract\n  option :to, required: true\n\n  def call(records)\n    records.map { |r| r.merge(field => Translator.call(r[field], to: to)) }\n  end\nend\nTranslate.register!\n```\n\nThe declared options drive validation, `--help`, `explain` output and typo\nsuggestions. Nothing else needs to know your step exists.\n\n## Trust\n\n`automation run file.rb` **executes Ruby**. Only run pipeline files you\ntrust, exactly as you would with a Rakefile or a Gemfile.\n\nFor untrusted input use the data path, which builds the same AST from JSON\nand executes no code:\n\n    $ automation run --safe pipeline.json\n\nThe registry is the boundary: an untrusted pipeline can only compose verbs\nyou chose to register.\n\n## Known limitations\n\n- A local variable with the same name as a step silently shadows the verb\n  inside a `define` block. Name spies and helpers distinctly.\n- Instance variables do not resolve inside the DSL block (`self` is the\n  builder). Bind them to locals first.\n- `PStore` is the default store; it rewrites the whole collection per\n  transaction and does not scale past a few megabytes. Swap in SQLite\n  behind `Automation::Store`'s three methods.\n- Steps registered as blocks cannot be compiled to standalone Ruby; use\n  plugin classes if you need that.\n\n## Licence\n\nMIT\n"}</code></pre>
        <p>Three deliberate choices in that README. It <strong>leads with the property that is unusual</strong> (pipelines are inspectable data) rather than with "a DSL for pipelines", which describes fifty gems. It <strong>shows real error output</strong>, because that is what convinces an experienced reader that the tool was used rather than published. And the <strong>known limitations section lists the two DSL traps I fell into</strong>, which costs nothing and is the difference between a user trusting your judgement and discovering the traps alone at midnight.</p>
        <h3>D2 · GitHub project description</h3>
        <blockquote>A Ruby DSL where pipelines are inspectable data: validated with file and line before anything runs, diagrammable, rewritable, and loadable from JSON with no code execution. No runtime dependencies. </blockquote>
        <p>Topics: <code>ruby</code>, <code>dsl</code>, <code>metaprogramming</code>, <code>ast</code>, <code>pipeline</code>, <code>automation</code>, <code>workflow</code>, <code>gem</code>, <code>plugin-architecture</code>, <code>interpreter</code>.</p>
        <h3>D3 · Performance considerations</h3>
        <ul>
          <li><strong>The DSL runs once</strong>, at load. Dispatch cost there is irrelevant: <code>method_missing</code> versus generated methods was 20 ns per call, and we chose generated methods for error messages, not speed.</li>
          <li><strong>The interpreter's overhead is a registry lookup and a few lambda calls per step</strong>, which is noise next to any step doing real I/O. Compiling (Part B) buys artefact independence, not meaningful speed.</li>
          <li><strong>Allocation is the usual Ruby cost.</strong> Frozen string literals took 10,000 allocations down to 2 in the measurement above; symbols allocate nothing; <code>Data</code> nodes cost about 3 objects each, which is a fair price for immutability and value equality.</li>
          <li><strong>Large datasets want lazy enumerators.</strong> Measured 0.0002 s over 2M lazy records against 0.38 s over 200k eager ones for a <code>first(5)</code> query. Steps must declare that they stream.</li>
          <li><strong>Threads help I/O-bound steps</strong> (0.201 s to 0.069 s for four concurrent sleeps) and never help CPU-bound ones. Bound the pool.</li>
          <li><strong>PStore rewrites the whole collection per transaction.</strong> It is the right default and the wrong choice past a few megabytes.</li>
        </ul>
        <h3>D4 · Security considerations</h3>
        <ul>
          <li><strong>A pipeline file is a program.</strong> <code>automation run file.rb</code> is <code>ruby file.rb</code> with extra steps. Treat pipeline files exactly as you treat Rakefiles: repository code, reviewed, never accepted from users.</li>
          <li><strong>The data path is the boundary.</strong> <code>from_h</code> builds the same AST from JSON with no callables. Bound it: a step limit, an identifier allow-list for names, and a recursive allow-list for option values. Reject handlers in data pipelines, because a handler is a block.</li>
          <li><strong>Safety is a property of the registry, not of the loader.</strong> If someone registers a <code>:shell</code> step, the data path executes shell commands as designed. Document which verbs are safe to expose.</li>
          <li><strong>Ruby has no sandbox.</strong> <code>$SAFE</code> was removed in 3.0 and never worked well. Do not attempt to sandbox untrusted Ruby in-process; use a separate process with OS-level limits, or do not execute it.</li>
          <li><strong>URLs in options are a request forgery risk.</strong> Our HTTP client already restricts schemes to http and https; a production version should also block private address ranges unless explicitly allowed, and cap redirects (we do) and response size (we do not, and should).</li>
          <li><strong>Publish with MFA.</strong> <code>rubygems_mfa_required</code> in the gemspec; review your <code>Gemfile.lock</code>; run <code>bundle audit</code> in CI.</li>
        </ul>
        <h3>D5 · What to put in your portfolio</h3>
        <p>
          <img className="mascot-left" src={img5.src} alt="The Mewlang cat, wearing glasses, looking confident" width="120" loading="lazy" />
          Present this as <strong>a study of what it takes to make a DSL trustworthy</strong>, not as "a pipeline runner". The interesting narrative is the sequence of realisations:
        </p>
        <ol>
          <li>A block plus <code>instance_eval</code> makes configuration read like a language, in about four lines. </li>
          <li>Doing that naively breaks in three silent ways, each demonstrated with real output: caller methods swallowed as steps, verbs shadowed by <code>Object</code> methods, typos accepted as valid.</li>
          <li>The fix that matters is not syntactic: <strong>build an AST and execute nothing</strong>, which then gives validation with file and line, dry runs, diagrams, diffs and rewriting.</li>
          <li>Declared plugin metadata drives validation, documentation and typo suggestions from one declaration. </li>
          <li>An executable configuration format is remote code execution, so there is a second, data-only front end sharing the same AST and engine.</li>
        </ol>
        <p>Keep a <code>docs/</code> folder with the <code>explain</code> output, a rendered Mermaid diagram, and the error-message screenshots. In an interview, the error messages are the artefact to lead with: <em>"here is a dynamic language producing compile-time-quality diagnostics, and here is how"</em>.</p>
        <p>Cut, if you want it tighter: the terminal-free extras (<code>graph</code> is charming but inessential), and the Milestone 2 <code>Pipeline</code> class, unless you keep it explicitly as the "before" half of the comparison and say so.</p>
        <h3>D6 · Interview questions someone could ask</h3>
        <table className="grid">
          <tbody>
            <tr>
              <th>Question</th>
              <th>What a strong answer includes</th>
            </tr>
            <tr>
              <td>How does the DSL work?</td>
              <td><code>instance_eval</code> changing <code>self</code>, <code>method_missing</code> or generated methods recording steps, and the fact that <em>nothing executes</em>: the block builds an AST.</td>
            </tr>
            <tr>
              <td>Why not just use YAML?</td>
              <td>Loops, conditionals, variables and an editor come free; the cost is that a config file is now a program, which is why there is a JSON path sharing the same AST.</td>
            </tr>
            <tr>
              <td>What goes wrong with <code>instance_eval</code>?</td>
              <td>All four identifier behaviours, plus the two silent failures with the actual symptoms you observed, plus the <code>BasicObject</code> and delegation fixes.</td>
            </tr>
            <tr>
              <td>Dynamic languages cannot catch errors early. Discuss.</td>
              <td>Mostly true, and here is the counter-move: capture <code>caller_locations</code> at build time, reflect on declared or inferred parameters, and report every problem at once with file and line. Then be honest that Racket does this properly at compile time.</td>
            </tr>
            <tr>
              <td>When is metaprogramming the wrong tool?</td>
              <td>When the names are known (use <code>define_method</code>), when the reader cannot follow it, when it breaks introspection, and any time the same result is achievable with a plain object. Cite the editor and tooling cost.</td>
            </tr>
            <tr>
              <td>How do you test a DSL?</td>
              <td>Assert the shape without running; ship spies and an isolated registry so users can test too; contract tests for plugins; an invariant test that building executes nothing.</td>
            </tr>
            <tr>
              <td>Tell me about a bug.</td>
              <td>The local variable that silently ate a verb, which caught you twice, including once after you had documented it. Then the conclusion: that is a design smell in the DSL, not only a mistake.</td>
            </tr>
            <tr>
              <td>How would you make it production-ready?</td>
              <td>Response size limits and SSRF protection on fetch, SQLite instead of PStore, structured logging, provenance for policy changes, JSON output for CI, and an opt-in compile step for auditable artefacts.</td>
            </tr>
            <tr>
              <td>Self-modifying pipelines: safe or not?</td>
              <td>Distinguish mutating a running pipeline from generating a successor; explain why only the second is defensible, and what idempotence and step limits protect against.</td>
            </tr>
            <tr>
              <td>Would you use Ruby again for this?</td>
              <td>Yes for the front end, and name the four features that make it. Then name the six bugs, all of which were dynamic-language failures caught by tests, and say what you would use instead if the priority were verified correctness rather than expressiveness.</td>
            </tr>
          </tbody>
        </table>
        <h3>D7 · Extensions worth building</h3>
        <ul>
          <li><strong>The compiler</strong> from Part B, and a <code>--compile</code> flag producing an auditable standalone file.</li>
          <li><strong>The language server</strong> from C5, which makes the DSL feel like a first-class language in an editor.</li>
          <li><strong>A scheduler</strong>: cron-like recurring runs with history, so <code>explain</code> can show a step's typical duration and failure rate from real data.</li>
          <li><strong>Web UI</strong> rendering the Mermaid graph with live run status.</li>
          <li><strong>A second front end</strong> (YAML or a tiny external syntax) proving the AST is genuinely the centre.</li>
        </ul>
        <hr />
        <h2><span className="num">Course 2 complete</span>What you built, and what it argues</h2>
        <p>A gem with twelve packages, a CLI, a plugin system, testing helpers for its users, two front ends sharing one AST, and 34 tests. More importantly, an argument you can make with evidence: <strong>the syntax is the least interesting part of a DSL</strong>. Anyone can make configuration look like a language in an afternoon with <code>instance_eval</code>. What makes it usable is everything that follows from refusing to execute while you parse.</p>
        <p>Ruby's answer to the curriculum's central question, stated precisely: <strong>problems where the shape of the solution is best expressed as a small language, and where you want to grow that language at run time, from inside the program, without a build step or a parser.</strong> Ruby makes the front end nearly free and hands you the responsibility for everything a compiler would have done: checking names, reporting locations, keeping tooling informed, and testing enough to survive the absence of a type checker.</p>
        <p>Course 5 takes the same ambition and moves it to compile time. Racket's macros turn a language definition into a function from syntax to syntax, checked before the program runs, with source locations carried automatically. When you get there, the thing to compare it against is Milestone 4's <code>caller_locations</code> frame counting and Part B's string-concatenating compiler. Both work. One is doing by hand what the other has as a primitive.</p>
        <footer className="end">
          <p>
            <img className="mascot-center" src={img6.src} alt="The Mewlang cat, viewed from behind, walking away" width="150" loading="lazy" />
            Instalment 10 of the five-course curriculum, and the end of Course 2. Next: Course 3, Perl, and the Text Archaeologist. Parts 0–2 first (what we are building, installation and CPAN, the language crash course), then twelve milestones turning ugly heterogeneous data into a searchable knowledge graph.
          </p>
        </footer>
         <Link className="button" href="/perl-course/instalment/">Next: Perl instalment</Link> 
      </div>
    </div>
  );
}
