'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { COURSE_NAV } from '../lib/course-nav.generated';
import walkPrev from '../courses/assets/expressions/right_to_left/walking.png';
import walkNext from '../courses/assets/expressions/left_to_right/walking.png';

// mdBook-style prev/next chapter buttons, fixed to the left/right edges of
// the viewport. Deliberately course-scoped only: COURSE_NAV (generated by
// scripts/migrate-pages.ts from PAGES) has no entries linking one course's
// last page to another course's first, so there is nothing here that could
// carry a reader from Go into Ruby, or off the course entirely — a route
// with no entry (the landing page, /overview/, an unwritten course) simply
// renders nothing.
export default function CourseNav() {
  const pathname = usePathname();
  const entry = COURSE_NAV[pathname];
  // Same theme scope as the page's own content (see any app/**/page.tsx's
  // outer <div>), so the buttons pick up the active course's palette —
  // these only ever render on a course page, so the prefix always matches.
  const themeMatch = /^\/([a-z]+)-course\//.exec(pathname);
  const themeClass = themeMatch ? `theme-${themeMatch[1]}` : '';
  if (!entry) return null;

  return (
    <div className={`course-nav-theme ${themeClass}`}>
      {entry.prev && (
        <Link
          href={entry.prev.href}
          className="course-nav-btn course-nav-prev"
          aria-label={`Previous: ${entry.prev.label}`}
        >
          <img src={walkPrev.src} alt="" loading="lazy" className="course-nav-mascot" />
          <span className="course-nav-caption">
            <span className="course-nav-arrow" aria-hidden="true">‹</span>
            {entry.prev.label}
          </span>
        </Link>
      )}
      {entry.next && (
        <Link
          href={entry.next.href}
          className="course-nav-btn course-nav-next"
          aria-label={`Next: ${entry.next.label}`}
        >
          <img src={walkNext.src} alt="" loading="lazy" className="course-nav-mascot" />
          <span className="course-nav-caption">
            {entry.next.label}
            <span className="course-nav-arrow" aria-hidden="true">›</span>
          </span>
        </Link>
      )}
    </div>
  );
}
