// Generated by scripts/migrate-pages.ts from PAGES — do not hand-edit.
// Prev/next chapter within the *same course only*, mdBook-style. A route
// with no entry here (the landing page, /overview/, an unwritten course)
// simply has no prev/next nav — see components/CourseNav.tsx.

export interface CourseNavLink {
  href: string;
  label: string;
}

export interface CourseNavEntry {
  prev: CourseNavLink | null;
  next: CourseNavLink | null;
}

export const COURSE_NAV: Record<string, CourseNavEntry> = {
  "/go-course/instalment/": { prev: null, next: { href: '/go-course/milestones/1-4/', label: "Milestones 1–4" } },
  "/go-course/milestones/1-4/": { prev: { href: '/go-course/instalment/', label: "Instalment" }, next: { href: '/go-course/milestones/5-8/', label: "Milestones 5–8" } },
  "/go-course/milestones/5-8/": { prev: { href: '/go-course/milestones/1-4/', label: "Milestones 1–4" }, next: { href: '/go-course/milestones/9-12/', label: "Milestones 9–12" } },
  "/go-course/milestones/9-12/": { prev: { href: '/go-course/milestones/5-8/', label: "Milestones 5–8" }, next: { href: '/go-course/milestones/end/', label: "Wrap-up" } },
  "/go-course/milestones/end/": { prev: { href: '/go-course/milestones/9-12/', label: "Milestones 9–12" }, next: null },
  "/ruby-course/instalment/": { prev: null, next: { href: '/ruby-course/milestones/1-4/', label: "Milestones 1–4" } },
  "/ruby-course/milestones/1-4/": { prev: { href: '/ruby-course/instalment/', label: "Instalment" }, next: { href: '/ruby-course/milestones/5-8/', label: "Milestones 5–8" } },
  "/ruby-course/milestones/5-8/": { prev: { href: '/ruby-course/milestones/1-4/', label: "Milestones 1–4" }, next: { href: '/ruby-course/milestones/9-12/', label: "Milestones 9–12" } },
  "/ruby-course/milestones/9-12/": { prev: { href: '/ruby-course/milestones/5-8/', label: "Milestones 5–8" }, next: { href: '/ruby-course/milestones/end/', label: "Wrap-up" } },
  "/ruby-course/milestones/end/": { prev: { href: '/ruby-course/milestones/9-12/', label: "Milestones 9–12" }, next: null },
  "/perl-course/instalment/": { prev: null, next: { href: '/perl-course/milestones/1-4/', label: "Milestones 1–4" } },
  "/perl-course/milestones/1-4/": { prev: { href: '/perl-course/instalment/', label: "Instalment" }, next: { href: '/perl-course/milestones/5-8/', label: "Milestones 5–8" } },
  "/perl-course/milestones/5-8/": { prev: { href: '/perl-course/milestones/1-4/', label: "Milestones 1–4" }, next: { href: '/perl-course/milestones/9-12/', label: "Milestones 9–12" } },
  "/perl-course/milestones/9-12/": { prev: { href: '/perl-course/milestones/5-8/', label: "Milestones 5–8" }, next: { href: '/perl-course/milestones/end/', label: "Wrap-up" } },
  "/perl-course/milestones/end/": { prev: { href: '/perl-course/milestones/9-12/', label: "Milestones 9–12" }, next: null },
  "/erlang-course/instalment/": { prev: null, next: { href: '/erlang-course/milestones/1-4/', label: "Milestones 1–4" } },
  "/erlang-course/milestones/1-4/": { prev: { href: '/erlang-course/instalment/', label: "Instalment" }, next: { href: '/erlang-course/milestones/5-8/', label: "Milestones 5–8" } },
  "/erlang-course/milestones/5-8/": { prev: { href: '/erlang-course/milestones/1-4/', label: "Milestones 1–4" }, next: { href: '/erlang-course/milestones/9-12/', label: "Milestones 9–12" } },
  "/erlang-course/milestones/9-12/": { prev: { href: '/erlang-course/milestones/5-8/', label: "Milestones 5–8" }, next: { href: '/erlang-course/milestones/end/', label: "Wrap-up" } },
  "/erlang-course/milestones/end/": { prev: { href: '/erlang-course/milestones/9-12/', label: "Milestones 9–12" }, next: null },
  "/racket-course/instalment/": { prev: null, next: { href: '/racket-course/milestones/1-4/', label: "Milestones 1–4" } },
  "/racket-course/milestones/1-4/": { prev: { href: '/racket-course/instalment/', label: "Instalment" }, next: { href: '/racket-course/milestones/5-8/', label: "Milestones 5–8" } },
  "/racket-course/milestones/5-8/": { prev: { href: '/racket-course/milestones/1-4/', label: "Milestones 1–4" }, next: { href: '/racket-course/milestones/9-12/', label: "Milestones 9–12" } },
  "/racket-course/milestones/9-12/": { prev: { href: '/racket-course/milestones/5-8/', label: "Milestones 5–8" }, next: { href: '/racket-course/milestones/end/', label: "Wrap-up" } },
  "/racket-course/milestones/end/": { prev: { href: '/racket-course/milestones/9-12/', label: "Milestones 9–12" }, next: null },
};
